import type { BaseNode, NodeSummary } from "../domain/types";
import {
  ReadOnlyError,
  type BacklinksIndex,
  type HierarchyIndex,
  type KnowledgeRepository,
} from "./repository";

/**
 * Reads the static "database" generated by scripts/build-index.ts into
 * `public/data/`. The only class that knows about paths and `fetch`.
 *
 * Keeps a trivial in-memory map of already-fetched files (a permitted
 * data-layer detail — there is no query cache above this; see app spec §4).
 */
export class StaticFileRepository implements KnowledgeRepository {
  private readonly base: string;
  private indexPromise?: Promise<NodeSummary[]>;
  private backlinksPromise?: Promise<BacklinksIndex>;
  private hierarchyPromise?: Promise<HierarchyIndex>;
  private readonly nodeCache = new Map<string, BaseNode | null>();

  constructor(baseUrl: string = import.meta.env.BASE_URL) {
    this.base = baseUrl.endsWith("/") ? baseUrl : baseUrl + "/";
  }

  private async fetchJson<T>(rel: string): Promise<T> {
    const res = await fetch(`${this.base}data/${rel}`);
    if (!res.ok) throw new Error(`Failed to load data/${rel}: ${res.status}`);
    return (await res.json()) as T;
  }

  getIndex(): Promise<NodeSummary[]> {
    return (this.indexPromise ??= this.fetchJson<NodeSummary[]>("index.json"));
  }

  private backlinks(): Promise<BacklinksIndex> {
    return (this.backlinksPromise ??= this.fetchJson<BacklinksIndex>("derived/backlinks.json"));
  }

  private hierarchy(): Promise<HierarchyIndex> {
    return (this.hierarchyPromise ??= this.fetchJson<HierarchyIndex>("derived/hierarchy.json"));
  }

  async getNode(id: string): Promise<BaseNode | null> {
    if (this.nodeCache.has(id)) return this.nodeCache.get(id)!;
    let node: BaseNode | null;
    try {
      node = await this.fetchJson<BaseNode>(`nodes/${id}.json`);
    } catch {
      node = null;
    }
    this.nodeCache.set(id, node);
    return node;
  }

  async getNodes(ids: string[]): Promise<BaseNode[]> {
    const nodes = await Promise.all(ids.map((id) => this.getNode(id)));
    return nodes.filter((n): n is BaseNode => n !== null);
  }

  async getBacklinks(id: string): Promise<string[]> {
    return (await this.backlinks())[id] ?? [];
  }

  async getChildren(id: string): Promise<string[]> {
    return (await this.hierarchy())[id]?.children ?? [];
  }

  async getParent(id: string): Promise<string | null> {
    return (await this.hierarchy())[id]?.parent ?? null;
  }

  async search(query: string): Promise<NodeSummary[]> {
    const q = query.trim().toLowerCase();
    if (!q) return [];
    const index = await this.getIndex();
    return index.filter(
      (n) =>
        n.title.toLowerCase().includes(q) ||
        n.tags.some((t) => t.toLowerCase().includes(q)),
    );
  }

  saveNode(): Promise<void> {
    throw new ReadOnlyError("saveNode");
  }

  deleteNode(): Promise<void> {
    throw new ReadOnlyError("deleteNode");
  }
}
